=== DavidAlvrz/52weS/MotoGP-Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified"
	targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="medidas" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="galeriaFotos" />
				<xs:element ref="galeriaVideos" />
				<xs:element ref="puntoOrigen" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="mundialClasificacion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="medidas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="anchura" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:positiveInteger">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:positiveInteger">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:date">
					<xs:attribute name="anio" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="hora">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:time">
					<xs:attribute name="zona_horaria" type="xs:string" />
					<xs:attribute name="formato" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="vueltas">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:positiveInteger">
					<xs:attribute name="unidad" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="tipo" type="xs:string" />
					<xs:attribute name="enlace" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriaFotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="archivo" type="xs:string" use="required" />
					<xs:attribute name="descripcion" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriaVideos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="archivo" type="xs:string" use="required" />
					<xs:attribute name="duracion" type="xs:string" />
					<xs:attribute name="descripcion" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoOrigen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudCoord" />
				<xs:element ref="latitudCoord" />
				<xs:element ref="altitudCoord" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitudCoord">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="longitudType">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="latitudCoord">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="latitudType">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="longitudType">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-180" />
			<xs:maxInclusive value="180" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="latitudType">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-90" />
			<xs:maxInclusive value="90" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="altitudCoord">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="altitudType">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="altitudType">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="8000" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="puntoFinal" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:positiveInteger">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoFinal">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudCoord" />
				<xs:element ref="latitudCoord" />
				<xs:element ref="altitudCoord" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:positiveInteger">
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="vencedor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombreVencedor" />
				<xs:element ref="tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombreVencedor" type="xs:string" />
	<xs:element name="tiempo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:duration">
					<xs:attribute name="unidad" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="mundialClasificacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="piloto" />
				<xs:element ref="piloto" />
				<xs:element ref="piloto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="piloto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="posicion" type="xs:positiveInteger" use="required" />
					<xs:attribute name="equipo" type="xs:string" />
					<xs:attribute name="puntos" type="xs:positiveInteger" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== DavidAlvrz/52weS/MotoGP-Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es circuito.xsd">

    <nombre>Circuit Ricardo Tormo</nombre>

    <medidas>
        <longitud unidad="m">4005</longitud>
        <anchura unidad="m">10</anchura>
    </medidas>

    <fecha anio="2025">2025-09-16</fecha>
    <hora zona_horaria="Europe/Madrid" formato="HH:MM">14:00:00</hora>
    <vueltas unidad="vueltas">27</vueltas>

    <localidad>Cheste</localidad>
    <pais>España</pais>
    <patrocinador>Motul</patrocinador>

    <referencias>
        <referencia tipo="web" enlace="https://www.circuitricardotormo.com/"> Web oficial</referencia>
        <referencia tipo="libro"
            enlace="https://entradas.circuitvalencia.com/circuitvalencia/events/referencia"> Compra
            de entradas </referencia>
        <referencia tipo="documento" enlace="https://es.wikipedia.org/wiki/Circuito_Ricardo_Tormo">
            Entrada wikipedia </referencia>
    </referencias>

    <galeriaFotos>
        <foto archivo="Panorama.jpg" descripcion="Circuito">../multimedia/circuito.png</foto>
    </galeriaFotos>

    <galeriaVideos>
        <video archivo="TODO.mp4" duracion="TODO">../multimedia/circuito.mp4</video>
    </galeriaVideos>

    <puntoOrigen>
        <longitudCoord unidad="deg">-0.7</longitudCoord>
        <latitudCoord unidad="deg">39.4</latitudCoord>
        <altitudCoord unidad="m">75</altitudCoord>
    </puntoOrigen>

    <tramos>

        <tramo>
            <distancia unidad="m">490</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.626365237</longitudCoord>
                <latitudCoord unidad="deg">39.486056226</latitudCoord>
                <altitudCoord unidad="m">146.67</altitudCoord>
            </puntoFinal>
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">44</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.626066543</longitudCoord>
                <latitudCoord unidad="deg">39.486356074</latitudCoord>
                <altitudCoord unidad="m">146.22</altitudCoord>
            </puntoFinal>
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">43</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.626049043</longitudCoord>
                <latitudCoord unidad="deg">39.486742136</latitudCoord>
                <altitudCoord unidad="m">146.26</altitudCoord>
            </puntoFinal>
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">316</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.627457653</longitudCoord>
                <latitudCoord unidad="deg">39.489370922</latitudCoord>
                <altitudCoord unidad="m">151.54</altitudCoord>
            </puntoFinal>
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">38</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.627788446</longitudCoord>
                <latitudCoord unidad="deg">39.489456029</latitudCoord>
                <altitudCoord unidad="m">151.79</altitudCoord>
            </puntoFinal>
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">32</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.628034771</longitudCoord>
                <latitudCoord unidad="deg">39.489293243</latitudCoord>
                <altitudCoord unidad="m">152.1</altitudCoord>
            </puntoFinal>
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">142</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.628265216</longitudCoord>
                <latitudCoord unidad="deg">39.488023206</latitudCoord>
                <altitudCoord unidad="m">151.17</altitudCoord>
            </puntoFinal>
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">161</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.627106454</longitudCoord>
                <latitudCoord unidad="deg">39.486828170</latitudCoord>
                <altitudCoord unidad="m">148.4</altitudCoord>
            </puntoFinal>
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">26</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.627231750</longitudCoord>
                <latitudCoord unidad="deg">39.486619888</latitudCoord>
                <altitudCoord unidad="m">148.5</altitudCoord>
            </puntoFinal>
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">118</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.628388533</longitudCoord>
                <latitudCoord unidad="deg">39.486017478</latitudCoord>
                <altitudCoord unidad="m">149.0</altitudCoord>
            </puntoFinal>
            <sector>1</sector>
        </tramo>

        <!-- SECTOR 2 -->

        <tramo>
            <distancia unidad="m">53</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.628899391</longitudCoord>
                <latitudCoord unidad="deg">39.486116281</latitudCoord>
                <altitudCoord unidad="m">149.7</altitudCoord>
            </puntoFinal>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">39</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.629109715</longitudCoord>
                <latitudCoord unidad="deg">39.486437318</latitudCoord>
                <altitudCoord unidad="m">150.25</altitudCoord>
            </puntoFinal>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">211</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.629147765</longitudCoord>
                <latitudCoord unidad="deg">39.488336723</latitudCoord>
                <altitudCoord unidad="m">154.97</altitudCoord>
            </puntoFinal>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">45</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.629489364</longitudCoord>
                <latitudCoord unidad="deg">39.488553665</latitudCoord>
                <altitudCoord unidad="m">156.3</altitudCoord>
            </puntoFinal>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">40</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.629833002</longitudCoord>
                <latitudCoord unidad="deg">39.488481863</latitudCoord>
                <altitudCoord unidad="m">156.75</altitudCoord>
            </puntoFinal>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">315</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.632700867</longitudCoord>
                <latitudCoord unidad="deg">39.486929289</latitudCoord>
                <altitudCoord unidad="m">162.33</altitudCoord>
            </puntoFinal>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">179</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.633702779</longitudCoord>
                <latitudCoord unidad="deg">39.485504600</latitudCoord>
                <altitudCoord unidad="m">162.8</altitudCoord>
            </puntoFinal>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">47</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.633450342</longitudCoord>
                <latitudCoord unidad="deg">39.485131705</latitudCoord>
                <altitudCoord unidad="m">161.61</altitudCoord>
            </puntoFinal>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">58</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.632935780</longitudCoord>
                <latitudCoord unidad="deg">39.485061269</latitudCoord>
                <altitudCoord unidad="m">159.7</altitudCoord>
            </puntoFinal>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">132</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.631635029</longitudCoord>
                <latitudCoord unidad="deg">39.485795628</latitudCoord>
                <altitudCoord unidad="m">156.7</altitudCoord>
            </puntoFinal>
            <sector>2</sector>
        </tramo>

        <!-- SECTOR 3 -->

        <tramo>
            <distancia unidad="m">108</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.631361181</longitudCoord>
                <latitudCoord unidad="deg">39.486729825</latitudCoord>
                <altitudCoord unidad="m">156.5</altitudCoord>
            </puntoFinal>
            <sector>3</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">52</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.630960767</longitudCoord>
                <latitudCoord unidad="deg">39.487064718</latitudCoord>
                <altitudCoord unidad="m">156.3</altitudCoord>
            </puntoFinal>
            <sector>3</sector>
        </tramo>

        <tramo>
            <distancia unidad="m">61</distancia>
            <puntoFinal>
                <longitudCoord unidad="deg">-0.630392500</longitudCoord>
